with open("./src/theme") as f:
    WINDOWTHEME = f.readline()


main_window_ico = r"./src/pic/main_window.png"
login_window_ico = r"./src/pic/login_window.png"
new_window_ico = r"./src/pic/new.png"
type_window_ico = r"./src/pic/new.png"
about_window_ico = r"./src/pic/about.png"

if WINDOWTHEME == "dark":
    login_ico = r"./src/pic/dark/login.png"
    sign_up_ico = r"./src/pic/dark/sign_up.png"
    choose_ico = r"./src/pic/dark/choose.png"
    search_ico = r"./src/pic/dark/search.png"
    refresh_ico = r"./src/pic/dark/refresh.png"
    add_ico = r"./src/pic/dark/add.png"
    remove_ico = r"./src/pic/dark/remove.png"
    update_ico = r"./src/pic/dark/update.png"
    start_ico = r"./src/pic/dark/start.png"
    add_type_ico = r"./src/pic/dark/add_type.png"
    remove_type_ico = r"./src/pic/dark/remove_type.png"
    file_ico = r"./src/pic/dark/file.png"
    type_ico = r"./src/pic/dark/type.png"
    about_ico = r"./src/pic/dark/about.png"
    show_ico = r"./src/pic/dark/show.png"
    clear_ico = r"./src/pic/dark/clear.png"
    ok_ico = r"./src/pic/dark/ok.png"
else:
    login_ico = r"./src/pic/light/login.png"
    sign_up_ico = r"./src/pic/light/sign_up.png"
    choose_ico = r"./src/pic/light/choose.png"
    search_ico = r"./src/pic/light/search.png"
    refresh_ico = r"./src/pic/light/refresh.png"
    add_ico = r"./src/pic/light/add.png"
    remove_ico = r"./src/pic/light/remove.png"
    update_ico = r"./src/pic/light/update.png"
    start_ico = r"./src/pic/light/start.png"
    add_type_ico = r"./src/pic/light/add_type.png"
    remove_type_ico = r"./src/pic/light/remove_type.png"
    file_ico = r"./src/pic/light/file.png"
    type_ico = r"./src/pic/light/type.png"
    about_ico = r"./src/pic/light/about.png"
    show_ico = r"./src/pic/light/show.png"
    clear_ico = r"./src/pic/light/clear.png"
    ok_ico = r"./src/pic/light/ok.png"